# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Title', models.CharField(max_length=200)),
                ('Product_Image', models.CharField(max_length=100)),
                ('Product_Description', models.CharField(max_length=500)),
                ('Product_Price', models.CharField(max_length=5)),
                ('Product_Rating', models.CharField(max_length=3)),
            ],
        ),
    ]
