# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Stock',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
