# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
