# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
