# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20161204_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Description',
        ),
    ]
