# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
